### ISSUE TITLE
Add parked cars?

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/Snooper#1]
Perhaps nice to add to Parked cars, in their info view you can see that the owner is doing something:
https://i.snag.gy/ziv607.jpg
Now it's a bit of a hassle for proper snooping: click parked car --> click owner name to follow him/her --> click the owner in the game.

**Comment by dymanoid** [comment]
I guess you mean not the parked car itself, but the owner's info, right? Because a parked car has no 'origin', it's just parked somewhere.

**Comment by Sipke82** [comment]
Well i ment the parked car, bu i didn't really thought it through, lets just close this :-)
